In [4]:
%reload_ext autoreload
%autoreload 2

import os
from toolkit import baseline_learner, utils, manager, arff

data = r"./test/datasets/creditapproval.arff"
my_learner = baseline_learner.BaselineLearner
session = manager.ToolkitSession(arff=data, learner=my_learner, eval_method="training", eval_parameter=None, print_confusion_matrix=False, normalize=False, random_seed=None)
# print(session.arff.data)
# session.arff.data=session.arff.data[:10,:]
# print(session.arff)


Dataset name: ./test/datasets/creditapproval.arff
Number of instances: 690
Number of attributes: 16
Learning algorithm: BaselineLearner
Evaluation method: training

Calculating accuracy on training set...
Time to train (in seconds): 0.0019936561584472656
Training set accuracy: 0.5550724637681159


In [3]:
import scipy

In [67]:
import subprocess
import os
print(os.getcwd())
data="./test/datasets/iris.arff"
args = ["L", "baseline", "A", data, "E", "training"]
command = [r"python", "./toolkit/manager.py", *args]
child = subprocess.Popen([*command], shell=False, stdout=subprocess.PIPE, 
                           stderr=subprocess.PIPE)

print(child.communicate(),child.returncode)

/media/taylor/eef4fe97-0587-4acb-b65d-f0ad5ed8d623/taylor/GitHub/realToolkit
(b'', b'Traceback (most recent call last):\n  File "./toolkit/manager.py", line 3, in <module>\n    from .supervised_learner import SupervisedLearner\nModuleNotFoundError: No module named \'__main__.supervised_learner\'; \'__main__\' is not a package\n') 1


In [75]:
%reload_ext autoreload
%autoreload 2

import os
from toolkit import baseline_learner, utils, manager, arff

data = r"./test/datasets/creditapproval.arff"

d=arff.Arff(data)
e=d.copy()
print(d.data.shape)
e._copy_and_slice_arff(d, 1, slice(2,4,))
print(e)

#d.slice([2:4,4]).data

SyntaxError: invalid syntax (<ipython-input-75-cc65ef4249ff>, line 15)

In [79]:
import numpy as np
np.nan == np.nan
np.inf == np.inf

@RELATION credit-rating
@ATTRIBUTE A1 {b, a}
@ATTRIBUTE A2 CONTINUOUS
@ATTRIBUTE A3 CONTINUOUS
@ATTRIBUTE A4 {u, y, l, t}
@ATTRIBUTE A5 {g, p, gg}
@ATTRIBUTE A6 {c, d, cc, i, j, k, m, r, q, w, x, e, aa, ff}
@ATTRIBUTE A7 {v, h, bb, j, n, z, dd, ff, o}
@ATTRIBUTE A8 CONTINUOUS
@ATTRIBUTE A9 {t, f}
@ATTRIBUTE A10 {t, f}
@ATTRIBUTE A11 CONTINUOUS
@ATTRIBUTE A12 {t, f}
@ATTRIBUTE A13 {g, p, s}
@ATTRIBUTE A14 CONTINUOUS
@ATTRIBUTE A15 CONTINUOUS
@ATTRIBUTE class {+, -}
@DATA
b, ?, ?, u, g, w, v, ?, t, t, ?, f, g, ?, ?, +
a, ?, ?, u, g, q, h, ?, t, t, ?, f, g, ?, ?, +
a, ?, ?, u, g, q, h, ?, t, f, ?, f, g, ?, ?, +
b, ?, ?, u, g, w, v, ?, t, t, ?, t, g, ?, ?, +
b, ?, ?, u, g, w, v, ?, t, f, ?, f, s, ?, ?, +
b, ?, ?, u, g, m, v, ?, t, f, ?, t, g, ?, ?, +
b, ?, ?, u, g, r, h, ?, t, f, ?, t, g, ?, ?, +
a, ?, ?, u, g, cc, v, ?, t, f, ?, f, g, ?, ?, +
b, ?, ?, y, p, k, h, ?, t, f, ?, f, g, ?, ?, +
b, ?, ?, y, p, w, v, ?, t, f, ?, t, g, ?, ?, +
b, ?, ?, u, g, c, h, ?, f, f, ?, t, g, ?, ?, +
b, ?, ?

'@RELATION credit-rating\n@ATTRIBUTE A1 {b, a}\n@ATTRIBUTE A2 CONTINUOUS\n@ATTRIBUTE A3 CONTINUOUS\n@ATTRIBUTE A4 {u, y, l, t}\n@ATTRIBUTE A5 {g, p, gg}\n@ATTRIBUTE A6 {c, d, cc, i, j, k, m, r, q, w, x, e, aa, ff}\n@ATTRIBUTE A7 {v, h, bb, j, n, z, dd, ff, o}\n@ATTRIBUTE A8 CONTINUOUS\n@ATTRIBUTE A9 {t, f}\n@ATTRIBUTE A10 {t, f}\n@ATTRIBUTE A11 CONTINUOUS\n@ATTRIBUTE A12 {t, f}\n@ATTRIBUTE A13 {g, p, s}\n@ATTRIBUTE A14 CONTINUOUS\n@ATTRIBUTE A15 CONTINUOUS\n@ATTRIBUTE class {+, -}\n@DATA\nb, ?, ?, u, g, w, v, ?, t, t, ?, f, g, ?, ?, +\na, ?, ?, u, g, q, h, ?, t, t, ?, f, g, ?, ?, +\na, ?, ?, u, g, q, h, ?, t, f, ?, f, g, ?, ?, +\nb, ?, ?, u, g, w, v, ?, t, t, ?, t, g, ?, ?, +\nb, ?, ?, u, g, w, v, ?, t, f, ?, f, s, ?, ?, +\nb, ?, ?, u, g, m, v, ?, t, f, ?, t, g, ?, ?, +\nb, ?, ?, u, g, r, h, ?, t, f, ?, t, g, ?, ?, +\na, ?, ?, u, g, cc, v, ?, t, f, ?, f, g, ?, ?, +\nb, ?, ?, y, p, k, h, ?, t, f, ?, f, g, ?, ?, +\nb, ?, ?, y, p, w, v, ?, t, f, ?, t, g, ?, ?, +\nb, ?, ?, u, g, c, h, ?, f

In [43]:
print(x)
x[1:5,(3,5,14)]

[[0.000e+00 3.083e+01 0.000e+00 ... 2.020e+02 0.000e+00 0.000e+00]
 [1.000e+00 5.867e+01 4.460e+00 ... 4.300e+01 5.600e+02 0.000e+00]
 [1.000e+00 2.450e+01 5.000e-01 ... 2.800e+02 8.240e+02 0.000e+00]
 ...
 [1.000e+00 2.525e+01 1.350e+01 ... 2.000e+02 1.000e+00 1.000e+00]
 [0.000e+00 1.792e+01 2.050e-01 ... 2.800e+02 7.500e+02 1.000e+00]
 [0.000e+00 3.500e+01 3.375e+00 ... 0.000e+00 0.000e+00 1.000e+00]]


array([[  0.,   8., 560.],
       [  0.,   8., 824.],
       [  0.,   9.,   3.],
       [  0.,   9.,   0.]])

In [189]:
%reload_ext autoreload
%autoreload 2
f = e.create_subset_arff([1,2,3,9],slice(0,3))

HERE <class 'toolkit.arff.Arff'>
HE
THERE <class 'toolkit.arff.Arff'>


In [183]:
e[0:None,:].shape==e.data.shape

True

In [190]:
print(f)

@RELATION Untitled_subset
@ATTRIBUTE 0 CONTINUOUS
@ATTRIBUTE 1 CONTINUOUS
@ATTRIBUTE 2 CONTINUOUS
@DATA
1.0, 58.67, 4.46
1.0, 24.5, 0.5
0.0, 27.83, 1.54
0.0, 42.5, 4.915



In [192]:
isinstance(f,type(e))

True

In [215]:
import numpy as np
col_idx = slice(8,-1)
print(e.data[col_idx])
#col_idx = [3,4,7,9]
requested_columns = np.r_(e.data[col_idx])
print(requested_columns)
print(col_idx.stop)


[[  0.    54.42   0.5    1.     1.     5.     1.     3.96   0.     1.
    0.     1.     0.   180.   314.     0.  ]]


TypeError: 'RClass' object is not callable

In [2]:
isinstance(r"THIS/that/theother.arff", str)

True

In [10]:
class klf:

    def m(self):
        print(type(self))

m = klf()
print(type(m) is klf)

print(type(m))
m.m()

True
<class '__main__.klf'>
<class '__main__.klf'>


In [12]:
import os
os.listdir()

['.coverage',
 '.git',
 'venv',
 'tox.ini',
 'toolkit',
 'setup.py',
 'venv2.7',
 'toolkit.egg-info',
 'README.md',
 'datasets',
 'Testing.ipynb',
 '.gitignore',
 '.ipynb_checkpoints',
 '.idea',
 '.tox',
 'run.py',
 'implemented',
 'test']

In [15]:
os.path.dirname("/this")

'/'